analytics_dbt:
  target: prod
  outputs:
    prod:
      type: trino
      host: trino.gdelt.svc.cluster.local
      port: 8080
      database: nessie
      schema: gold
      user: trino
      threads: 2
      session_properties:
        query_max_run_time: 30m
